"""Academic planner contracts, deterministic allocation, and workflow."""

from app.agents.academic_planner.allocator import allocate_plan, priority_score
from app.agents.academic_planner.contracts import (
    AmbiguousFact,
    Assessment,
    AssessmentType,
    AvailabilityWindow,
    CheckinExtraction,
    CheckinProposal,
    DailyPlan,
    FixedCommitment,
    IncompleteBlock,
    PlanCritique,
    PlannerFacts,
    ProposedChange,
    StudyBlock,
    WorkBreakdown,
)
from app.agents.academic_planner.sync import (
    AcademicClarificationService,
    AcademicNotionSync,
    AcademicNotionSyncResult,
)
from app.agents.academic_planner.workflow import (
    AcademicPlannerStore,
    AcademicSynchronizer,
    NotionAcademicWriter,
    PlannerDelivery,
    PlannerModelGateway,
    build_daily_plan,
    configure_academic_runtime,
    confirm_checkin_proposal,
    create_checkin_proposal,
    run_academic_planner,
    run_end_of_day_checkin,
    run_morning_plan,
)

__all__ = [
    "AcademicClarificationService",
    "AcademicNotionSync",
    "AcademicNotionSyncResult",
    "AcademicPlannerStore",
    "AcademicSynchronizer",
    "AmbiguousFact",
    "Assessment",
    "AssessmentType",
    "AvailabilityWindow",
    "CheckinExtraction",
    "CheckinProposal",
    "DailyPlan",
    "FixedCommitment",
    "IncompleteBlock",
    "NotionAcademicWriter",
    "PlanCritique",
    "PlannerDelivery",
    "PlannerFacts",
    "PlannerModelGateway",
    "ProposedChange",
    "StudyBlock",
    "WorkBreakdown",
    "allocate_plan",
    "build_daily_plan",
    "configure_academic_runtime",
    "confirm_checkin_proposal",
    "create_checkin_proposal",
    "priority_score",
    "run_academic_planner",
    "run_end_of_day_checkin",
    "run_morning_plan",
]
